// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var React       = require("react");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

var component = ReasonReact.statelessComponent("ChuckJoke");

function make(joke, _) {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function (_, _$1) {
      return React.createElement("div", {
                  className: "ChuckJoke"
                }, React.createElement("img", {
                      src: joke[/* icon_url */0]
                    }), React.createElement("h2", undefined, joke[/* value */1]));
    });
  return newrecord;
}

exports.component = component;
exports.make      = make;
/* component Not a pure module */
