// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var Json_decode = require("bs-json/lib/js/src/json_decode.js");

function parseChuckJokeJson(json) {
  return /* record */[
          /* icon_url */Json_decode.field("icon_url", Json_decode.string, json),
          /* value */Json_decode.field("value", Json_decode.string, json)
        ];
}

var chuckApi = "https://api.chucknorris.io/jokes/random?category=dev";

function fetchJoke() {
  return fetch(chuckApi).then((function (prim) {
                  return prim.json();
                })).then((function (json) {
                return Promise.resolve(parseChuckJokeJson(json));
              }));
}

exports.parseChuckJokeJson = parseChuckJokeJson;
exports.chuckApi           = chuckApi;
exports.fetchJoke          = fetchJoke;
/* No side effect */
