// Generated by BUCKLESCRIPT VERSION 1.8.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe     = require("reason-react/lib/js/src/reactDOMRe.js");
var ReasonReact    = require("reason-react/lib/js/src/reasonReact.js");
var ChuckNorrisApp = require("./chuckNorrisApp.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, ChuckNorrisApp.make(/* array */[])), "root");

/*  Not a pure module */
